name: Create Release and Update Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

       # Installer Ruby et Bundler (pour gérer les dépendances)
      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install bundler

      # Installer le générateur de changelog avec Bundler
      - name: Install changelog generator with Bundler
        run: |
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'github_changelog_generator'" >> Gemfile
          bundle install

      # Générer le changelog
      - name: Generate changelog
        run: |
          bundle exec github_changelog_generator --future-release ${{ github.sha }}

      # Ajouter le changelog généré et le commit
      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update changelog for release"
          git push

      # Créer une release sur GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.html
            *.js
            *css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
