name: Create Release and Generate Changelog

on:
  push:
    branches:
      - main  # Exécuter sur chaque push vers la branche 'main'
  pull_request:
    branches:
      - main  # Exécuter également sur les pull requests vers 'main'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.html
          *.js
          *.css
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
