name: Create Release and Update Changelog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v2

      # Installer Ruby et Bundler (pour gérer les dépendances)
      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full build-essential
          gem install bundler

      # Installer le générateur de changelog avec --user-install
      - name: Install changelog generator
        run: |
          # Installer github_changelog_generator dans un répertoire spécifique à l'utilisateur
          gem install github_changelog_generator --user-install

          # Ajouter le répertoire des gems à la variable PATH
          echo "export PATH=\$PATH:\$HOME/.gem/ruby/2.7.0/bin" >> $GITHUB_ENV

      # Vérifier l'installation du gem
      - name: Verify gem installation
        run: |
          gem list | grep github_changelog_generator

      # Générer le changelog
      - name: Generate changelog
        run: |
          github_changelog_generator --future-release ${{ github.sha }}

      # Ajouter le changelog généré et le commit
      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Update changelog for release"
          git push

      # Build project (par exemple avec Node.js)
      - name: Build project
        run: |
          npm install
          npm run build  # Les artefacts seront générés dans 'dist/'

      # Créer la release sur GitHub
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            *.html
            *.js
            *.css
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
